name: Continuous Integration for Grails 3.x

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Ensure Gradle Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle 4.5 (Grails 3.3.5)
        run: ./gradlew clean assemble -x test --stacktrace --info

      - name: Docker Hub Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Compose Build
        run: docker compose build

      - name: Push to Docker Hub Container Registry
        run: |
         docker tag gestao-atividade ${{ secrets.DOCKER_USERNAME }}/gestao-atividade:${{ github.run_id }}
         docker tag gestao-atividade ${{ secrets.DOCKER_USERNAME }}/gestao-atividade:latest
         docker push ${{ secrets.DOCKER_USERNAME }}/gestao-atividade:${{ github.run_id }}
         docker push ${{ secrets.DOCKER_USERNAME }}/gestao-atividade:latest
